---
# tasks file for osm2pgsql
- name: Create Image folder
  file:
    path: '{{ image_files }}/osm2pgsql'
    state: directory
- name: Render main.py
  template:
    src: main.j2.py
    dest: '{{ image_files }}/osm2pgsql/main.py'
- name: Render Dockerfile
  template:
    src: Dockerfile.j2
    dest: '{{ image_files }}/osm2pgsql/Dockerfile'
- name: Build Image
  shell:
    cmd: 'docker image build . -t osm2pgsql:{{ image_version }}'
    chdir: '{{ image_files }}/osm2pgsql'
- name: Tag Image (repo only)
  shell:
    cmd: 'docker tag osm2pgsql:{{ image_version }} {{ repository }}/osm2pgsql:{{ image_version }}'
    chdir: '{{ image_files }}/osm2pgsql'
  when: repository is defined
- name: Push Image to repo 
  shell:
    cmd: 'docker push {{ repository }}/osm2pgsql:{{ image_version }}'
  when: repository is defined
- name: Render Deployment
  template:
    src: osm2pgsql_deployment.j2.yaml
    dest: '{{ manifest_folder }}/osm2pgsql_deployment.yaml'
#- name: Render Service 
#  template:
#    src: osm2pgsql_service.j2.yaml
#    dest: '{{ manifest_folder }}/osm2pgsql_service.yaml'
- name: Apply Deployment 
  shell:
    cmd: 'kubectl create -f osm2pgsql_deployment.yaml -n {{ gisnamespace }}'
    chdir: '{{ manifest_folder }}'
  ignore_errors: true
#- name: Apply Service
#  shell:
#    cmd: 'kubectl create -f osm2pgsql_service.yaml -n {{ gisnamespace }}'
#    chdir: '{{ manifest_folder }}'
#  ignore_errors: true



