FROM ubuntu:20.04

LABEL maintainer="GeoGeekSuite <marco@bradtke.eu>"

RUN apt update
RUN apt install software-properties-common -y
RUN add-apt-repository -y ppa:ubuntugis/ppa
RUN apt update
RUN apt install python3-pip -y

RUN apt install gdal-bin -y
RUN apt install unzip -y
RUN apt install curl -y

RUN pip3 install jupyter
RUN pip3 install ipyleaflet
RUN pip3 install psycopg2-binary
RUN pip3 install pandas

CMD jupyter notebook --ip 0.0.0.0 --allow-root --NotebookAp.token='{{ password }}'

