---
- hosts: local
  vars_files:
  - ./credentials.yaml
  - ./environment.yaml
  - ./global_defaults.yaml
  tasks:
  - name: Scale Down
    shell:
        cmd: 'kubectl scale deployment {{ item.name }} --replicas=0 -n {{ gisnamespace }}'
    with_items: '{{ deployments }}'
    tags: ['never','scaledown']
  - name: Scale Up
    shell:
      cmd: 'kubectl scale deployment {{ item.name }} --replicas={{ item.replicas }} -n {{ gisnamespace }}'
    with_items: '{{ deployments }}'
    tags: ['never','scaleup']
  roles:
  - { role: kube,
        tags: kube }
  - { role: geodatabase,
        tags: geodatabase }
  - { role: pgadmin,
        tags: pgadmin }
  - { role: jupyter,
        tags: jupyter }
  - { role: ingress,
       tags: ingress }
  - { role: gdal,
       tags: gdal }
  - { role: elastic,
       tags: elastic }
  - { role: kibana,
       tags: kibana }
  - { role: jobregistry,
       tags: jobregistry }