FROM ubuntu:{{osm2pg.ubuntu_version}}
ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update && apt-get install -y apt-transport-https
RUN apt-get install osm2pgsql -y
#RUN apt install software-properties-common -y
#RUN add-apt-repository ppa:ubuntugis/ppa
#RUN apt update
#RUN apt install osm2pgsql -y
RUN apt install python3-pip -y
RUN pip3 install flask
#RUN pip3 install psycopg2-binary
#RUN pip3 install requests
{% for package in python.pip_common %}
RUN pip3 install {{ package }}
{% endfor %}

WORKDIR /opt/osm2pgsql
COPY main.py main.py

CMD ["python3", "-u", "main.py"]