apiVersion: apps/v1
kind: Deployment
metadata:
  name: osm2pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
       app: osm2pgsql
  template:
    metadata:
      labels:
        app: osm2pgsql
    spec:
      containers:
        - name: osm2pgsql
{% if repository is undefined %}
          image: 'osm2pgsql:{{ image_version }}'
{% else %}
          image: '{{ repository }}/osm2pgsql:{{ image_version }}'
{% endif %}
          env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: PGPASSWORD
          - name: LOG_LEVEL
            value: DEBUG
          - name: PYTHONPATH
            value: /opt/cobra-python-packages
          ## PG Environment variables
          - name: PGHOST
            value: postgres
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: postgres
          - name: PGUSER
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: PGPASSWORD
          - name: OPSDATABASE
            value: ops
          - name: DOWNLOAD_FOLDER
            value: './download'
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          command: ["python3", "main.py"]
          volumeMounts:
            - mountPath: /opt/cobra-python-packages
              name: devlibs
            - mountPath: /download
              name: download
            - mountPath: /styles
              name: styles
      volumes:
        - name: devlibs
          hostPath:
            path: {{ local_lib_path }}/python
            type: DirectoryOrCreate
        - name: download
          persistentVolumeClaim:
            claimName: download-claim
        - name: styles
          persistentVolumeClaim:
            claimName: styles-claim
 
