apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ geodatabase.dbname }}
  POSTGRES_USER: {{ geodatabase.dbadmin }}
  POSTGRES_PASSWORD: {{ geodatabase.dbpw }}