FROM ubuntu:{{ gdal.ubuntu_version }}

RUN apt update
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:ubuntugis/ppa
RUN apt update
RUN apt install gdal-bin -y
RUN apt install -y python3-pip
RUN pip3 install flask
RUN pip3 install psycopg2-binary

WORKDIR /opt/gdal
COPY main.py main.py

CMD ["python3", "-u", "main.py"]



