apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdal
spec:
  replicas: 1
  selector:
    matchLabels:
       app: gdal
  template:
    metadata:
      labels:
        app: gdal
    spec:
      containers:
        - name: gdal
          image: gdal
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: POSTGRES_PASSWORD
          - name: LOG_LEVEL
            value: DEBUG
          - name: PYTHONPATH
            value: /opt/cobra-python-packages
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          command: ["python3", "main.py"]
          volumeMounts:
            - mountPath: /opt/cobra-python-packages
              name: devlibs
      volumes:
        - name: devlibs
          hostPath:
            path: {{ local_lib_path }}/python
            type: DirectoryOrCreate
 
