FROM {{geoserver.java_image}}:{{geoserver.java_image_version}}

WORKDIR /usr/share/geoserver
RUN wget https://sourceforge.net/projects/geoserver/files/GeoServer/{{geoserver.version}}/geoserver-{{geoserver.version}}-bin.zip
RUN unzip geoserver-{{geoserver.version}}-bin.zip
COPY users.xml /usr/share/geoserver/data_dir/security/usergroup/default/users.xml
COPY roles.xml /usr/share/geoserver/data_dir/security/role/default/roles.xml

WORKDIR /usr/share/geoserver/bin
CMD sh startup.sh