apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{ item.name }}-volume'
  labels:
    type: '{{ item.type }}'
spec:
  storageClassName: manual
  capacity:
    storage: '{{ item.size }}'
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '{{ item.path }}'
  claimRef:
    name: '{{ item.name }}-claim'
    namespace: '{{ gisnamespace }}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ item.name }}-claim'
spec:
  storageClassName: manual
  volumeName: '{{ item.name }}-volume'
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '{{ item.size }}'