apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jupyter
  annotations:
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: jupyter.localhost
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: jupyter
            port:
              number: 8888

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-geoserver
#  annotations:
#    kubernetes.io/ingress.class: "{{ ingress_class }}"
#spec:
#  rules:
#  - host: geoserver.localhost
#    http:
#      paths:
#      - path: /
#        pathType: ImplementationSpecific
#        backend:
#          service:
#            name: geoserver
#            port:
#              number: 8080
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-pgadmin
#  annotations:
#    # use the shared ingress-nginx
#    kubernetes.io/ingress.class: "{{ ingress_class }}"
#spec:
#  rules:
#  - host: localhost
#    http:
#      paths:
#      - path: /
#        pathType: ImplementationSpecific
#        backend:
#          service:
#            name: pgadmin
#            port:
#              number: 80
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-pgadmin
  annotations:
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: pgadmin.localhost
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: pgadmin
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-pgservice
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: postgres.localhost
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: postgres
            port:
              number: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-kibana
  annotations:
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: kibana.localhost
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: kibana
            port:
              number: 5601
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-webhoster
  annotations:
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: webhoster
            port:
              number: 80