apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'ingress-jupyter-{{ item }}'
  annotations:
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: 'jupyter.{{ item }}'
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: jupyter
            port:
              number: 8888

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: 'ingress-geoserver-{{ item }}'
#  annotations:
#    kubernetes.io/ingress.class: "{{ ingress_class }}"
#spec:
#  rules:
#  - host: 'geoserver.{{ item }}'
#    http:
#      paths:
#      - path: /
#        pathType: ImplementationSpecific
#        backend:
#          service:
#            name: geoserver
#            port:
#              number: 8080
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'ingress-pgadmin-{{ item }}'
  annotations:
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: 'pgadmin.{{ item }}'
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: pgadmin
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'ingres-pgservice-{{ item }}'
  annotations:
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: 'postgres.{{ item }}'
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: postgres
            port:
              number: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'ingres-kibana-{{ item }}'
  annotations:
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: 'kibana.{{ item }}'
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: kibana
            port:
              number: 5601
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'ingres-webhoster-{{ item }}'
  annotations:
    kubernetes.io/ingress.class: "{{ ingress_class }}"
spec:
  rules:
  - host: '{{ item }}'
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: webhoster
            port:
              number: 80