apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhoster
spec:
  replicas: 1
  selector:
    matchLabels:
       app: webhoster
  template:
    metadata:
      labels:
        app: webhoster
    spec:
      containers:
        - name: webhoster
          image: {{ webhoster.image }}:{{ webhoster.tag }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/
              name: webroot
            - mountPath: /usr/local/apache2/htdocs/export
              name: export
      volumes:
        - name: webroot
          hostPath:
            path: '{{ project_folder }}/web'
            type: DirectoryOrCreate
        - name: export
          persistentVolumeClaim:
            claimName: export-claim

 