apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhoster
spec:
  replicas: 1
  selector:
    matchLabels:
       app: webhoster
  template:
    metadata:
      labels:
        app: webhoster
    spec:
      containers:
        - name: webhoster
          image: httpd:2.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/
              name: webroot
      volumes:
        - name: webroot
          hostPath:
            path: '{{ project_folder }}/web'
            type: DirectoryOrCreate

 