apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
       app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
          env:
          - name: discovery.type
            value: "single-node"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9200
